version: "3.9"   # compose 파일 버전

services:
  postgres:
    image: postgres:16
    container_name: pg
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: moodin-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/db
      DB_USERNAME: user
      DB_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  pgdata:
