server:
  port: 8080

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

# (DB 없으면 아래는 생략 가능)
#  datasource:
#    url: jdbc:h2:mem:testdb;MODE=MySQL
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
